plugins {
	id 'java'
	id 'org.springframework.boot' version "$bootVersion"
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.google.protobuf' version '0.10.0'
}

group = 'com.example'
version = '1.1.2-SNAPSHOT'

def toolchainVersion() {
	if (project.hasProperty('testToolchain')) {
		return project.property('testToolchain').toString().toInteger()
	}
	return 17
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(toolchainVersion())
	}
}

repositories {
	mavenLocal()
	mavenCentral()
	maven { url 'https://repo.spring.io/milestone' }
	maven { url 'https://repo.spring.io/snapshot' }
}

if (project.hasProperty('springGrpcVersion')) ext['spring-grpc.version'] = project.property('springGrpcVersion')

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-grpc-client'

	testImplementation 'org.springframework.boot:spring-boot-starter-grpc-client-test'
	testImplementation 'org.springframework.boot:spring-boot-web-server'
	testImplementation 'org.springframework.experimental.boot:spring-boot-testjars-maven:0.4.0.0'

	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}


tasks.named('test') {
	useJUnitPlatform()
}

protobuf {
	plugins {
		grpc {}
	}
}
