plugins {
	id 'java'
	id 'org.springframework.boot' version "$bootVersion"
	id 'io.spring.dependency-management' version '1.1.7'
	id 'org.graalvm.buildtools.native' version '1.1.8'
	id 'com.google.protobuf' version '0.10.0'
}

group = 'com.example'
version = '1.1.2-SNAPSHOT'

if (project.hasProperty('springGrpcVersion')) ext['spring-grpc.version'] = project.property('springGrpcVersion')

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenLocal()
	mavenCentral()
	maven { url 'https://repo.spring.io/milestone' }
	maven { url 'https://repo.spring.io/snapshot' }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-grpc-server'
	implementation 'org.springframework.boot:spring-boot-starter-security'

	testImplementation 'org.springframework.boot:spring-boot-starter-grpc-client-test'

	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
	useJUnitPlatform()
	testLogging.showStandardStreams = true
	outputs.upToDateWhen { false }
}

protobuf {
	plugins {
		grpc {}
	}
}

