name: Check Samples (Gradle)

on:
  workflow_dispatch:

jobs:
  check_samples:
    name: Check Samples project
    if: ${{ github.repository == 'spring-projects/spring-grpc' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # latest stable: Spring Boot 4.1.1 pins Spring gRPC 1.1.1
          - javaVersion: 25
            distribution: 'liberica'
            bootVersion: '4.1.1'
            springGrpcVersion: '1.1.1'
          - javaVersion: 17
            distribution: 'temurin'
            bootVersion: '4.1.1'
            springGrpcVersion: '1.1.1'
          # latest snapshot
          - javaVersion: 25
            distribution: 'liberica'
            bootVersion: '4.1.2-SNAPSHOT'
            springGrpcVersion: '1.1.2-SNAPSHOT'
          - javaVersion: 17
            distribution: 'temurin'
            bootVersion: '4.1.2-SNAPSHOT'
            springGrpcVersion: '1.1.2-SNAPSHOT'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java ${{ matrix.javaVersion }} ${{ matrix.distribution }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.javaVersion }}
          distribution: ${{ matrix.distribution }}
          cache: gradle

      - name: Build and run samples w/ Java 25 $ {{ matrix.distribution }} (non-kotlin)
        if: ${{ matrix.javaVersion == 25 }}
        run: |
          cd samples
          ./gradlew clean build \
            -x :grpc-server-kotlin:build \
            -PtestToolchain=25 \
            -PbootVersion=${{ matrix.bootVersion }} \
            -PspringGrpcVersion=${{ matrix.springGrpcVersion }} \
            --rerun-tasks --no-build-cache \
            build

      - name: Setup Java 24 for grpc-server-kotlin w/ Java 24
        if: ${{ matrix.javaVersion == 25 }}
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: ${{ matrix.distribution }}
          cache: gradle
      - name: Build and run samples w/ Java grpc-server-kotlin w/ Java 24
        if: ${{ matrix.javaVersion == 25 }}
        run: |
          cd samples
          ./gradlew :grpc-server-kotlin:build \
            -PtestToolchain=24 \
            -PbootVersion=${{ matrix.bootVersion }} \
            -PspringGrpcVersion=${{ matrix.springGrpcVersion }} \
            --rerun-tasks --no-build-cache

      - name: Build and run samples w/ Java ${{ matrix.javaVersion }} ${{ matrix.distribution }}
        if: ${{ matrix.javaVersion != 25 }}
        run: |
          cd samples
          ./gradlew clean build \
            -PtestToolchain="${{ matrix.javaVersion }}" \
            -PbootVersion=${{ matrix.bootVersion }} \
            -PspringGrpcVersion=${{ matrix.springGrpcVersion }} \
            --rerun-tasks --no-build-cache

      - name: Upload Build Reports (Java ${{ matrix.javaVersion }} ${{ matrix.distribution }})
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '*/target/surefire-reports/*.*'
          retention-days: 3
