name: Check Samples (Spring Boot compatability)

on:
  workflow_dispatch:

jobs:
  check_samples:
    name: Check Samples project
    if: ${{ github.repository == 'spring-projects/spring-grpc' }}
    strategy:
      matrix:
        include:
          - javaVersion: 17
            springBootVersion: "4.0.0-SNAPSHOT"
            springGrpcVersion: "1.0.0-SNAPSHOT"
          - javaVersion: 25
            springBootVersion: "4.0.0-SNAPSHOT"
            springGrpcVersion: "1.0.0-SNAPSHOT"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: spring-io/spring-gradle-build-action@v2
      - name: Check samples project
        env:
          JAVA_VERSION: ${{ matrix.javaVersion }}
          BOOT_VERSION: ${{ matrix.springBootVersion }}
          SPRING_GRPC_VERSION: ${{ matrix.springGrpcVersion }}
        run: |
          cd samples   
          ./gradlew \
            --init-script ./sample-apps-check-ci.gradle \
            -PtestToolchain="$JAVA_VERSION" \
            -PspringBootVersion="$BOOT_VERSION" \
            -PspringGrpcVersion="$SPRING_GRPC_VERSION" \
            --rerun-tasks --no-build-cache \
            build
