name: CI PRs (main)

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'

jobs:
  build_and_verify:
    name: Build and Verify
    if: ${{ github.repository == 'spring-projects/spring-grpc' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 25 (main)
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'liberica'
          cache: maven
      - name: Build and test
        run: |
          ./mvnw -B clean install
      - name: Set up JDK 17 (run samples)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run samples w/ Java 17
        run: |
          pushd samples > /dev/null
          ../mvnw clean install \
              -Dmaven-checkstyle-plugin.config.location=../src/checkstyle
          popd > /dev/null
      - name: Capture Test Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '*/target/surefire-reports/*.*'
          retention-days: 3
